import type {
  GardenFlower,
  GardenGrass,
} from "../components/garden/types";

/**
 * Garden composition — v2 art direction pass.
 *
 * Design intent:
 *  - Foreground: dramatic scale (1.7–2.4), flowers bleed past both edges,
 *    irregular spacing to feel organic rather than evenly distributed.
 *  - Midground: medium scale (0.95–1.25), denser than before.
 *  - Background: small (0.50–0.78), covers full width including edges.
 *
 * The SVG viewBox is "0 0 100 110" with preserveAspectRatio="xMidYMax slice",
 * so negative x values and values > 100 are intentionally cut by the viewport
 * edges — this makes the scene feel larger than the screen.
 */
export const GARDEN_FLOWERS: GardenFlower[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // BACKGROUND  (scale 0.50–0.78, opacity 0.45 via CSS)
  // ─────────────────────────────────────────────────────────────────────────

  {
    id: "bg-tulip-far-left",
    type: "tulip",
    depth: "background",
    x: -3,
    y: 95,
    scale: 0.60,
    rotation: -9,
    variant: 2,
  },
  {
    id: "bg-tulip-1",
    type: "tulip",
    depth: "background",
    x: 8,
    y: 94,
    scale: 0.58,
    rotation: -6,
    variant: 0,
  },
  {
    id: "bg-gerbera-1",
    type: "gerbera",
    depth: "background",
    x: 18,
    y: 93,
    scale: 0.55,
    rotation: 5,
    variant: 1,
    visibleIn: ["day", "sunset", "night"],
  },
  {
    id: "bg-tulip-2",
    type: "tulip",
    depth: "background",
    x: 29,
    y: 96,
    scale: 0.65,
    rotation: 4,
    variant: 1,
  },
  {
    id: "bg-tulip-3",
    type: "tulip",
    depth: "background",
    x: 41,
    y: 94,
    scale: 0.52,
    rotation: -3,
    variant: 2,
  },
  {
    id: "bg-gerbera-2",
    type: "gerbera",
    depth: "background",
    x: 53,
    y: 93,
    scale: 0.56,
    rotation: 7,
    variant: 0,
    visibleIn: ["day", "sunset"],
  },
  {
    id: "bg-tulip-4",
    type: "tulip",
    depth: "background",
    x: 63,
    y: 95,
    scale: 0.70,
    rotation: -5,
    variant: 0,
  },
  {
    id: "bg-gerbera-3",
    type: "gerbera",
    depth: "background",
    x: 74,
    y: 94,
    scale: 0.54,
    rotation: 4,
    variant: 2,
    visibleIn: ["sunset", "night"],
  },
  {
    id: "bg-tulip-5",
    type: "tulip",
    depth: "background",
    x: 85,
    y: 95,
    scale: 0.63,
    rotation: -7,
    variant: 1,
  },
  {
    id: "bg-tulip-far-right",
    type: "tulip",
    depth: "background",
    x: 97,
    y: 94,
    scale: 0.58,
    rotation: 5,
    variant: 2,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // MIDGROUND  (scale 0.95–1.25, opacity 0.82 via CSS)
  // ─────────────────────────────────────────────────────────────────────────

  {
    id: "mid-tulip-far-left",
    type: "tulip",
    depth: "midground",
    x: -1,
    y: 101,
    scale: 1.02,
    rotation: -11,
    variant: 1,
  },
  {
    id: "mid-gerbera-1",
    type: "gerbera",
    depth: "midground",
    x: 9,
    y: 102,
    scale: 0.96,
    rotation: 9,
    variant: 0,
    visibleIn: ["day", "sunset", "night"],
  },
  {
    id: "mid-tulip-1",
    type: "tulip",
    depth: "midground",
    x: 19,
    y: 100,
    scale: 1.08,
    rotation: 5,
    variant: 0,
    essential: true,
  },
  {
    id: "mid-gerbera-2",
    type: "gerbera",
    depth: "midground",
    x: 31,
    y: 103,
    scale: 0.98,
    rotation: -4,
    variant: 2,
    visibleIn: ["sunset"],
  },
  {
    id: "mid-tulip-2",
    type: "tulip",
    depth: "midground",
    x: 42,
    y: 99,
    scale: 1.18,
    rotation: 3,
    variant: 2,
  },
  {
    id: "mid-gerbera-3",
    type: "gerbera",
    depth: "midground",
    x: 52,
    y: 102,
    scale: 1.05,
    rotation: -6,
    variant: 1,
    visibleIn: ["day", "sunset", "night"],
    essential: true,
  },
  {
    id: "mid-tulip-3",
    type: "tulip",
    depth: "midground",
    x: 63,
    y: 100,
    scale: 1.12,
    rotation: -5,
    variant: 0,
  },
  {
    id: "mid-gerbera-4",
    type: "gerbera",
    depth: "midground",
    x: 73,
    y: 103,
    scale: 1.00,
    rotation: 6,
    variant: 2,
    visibleIn: ["sunset", "night"],
    essential: true,
  },
  {
    id: "mid-tulip-4",
    type: "tulip",
    depth: "midground",
    x: 83,
    y: 101,
    scale: 1.15,
    rotation: -8,
    variant: 1,
  },
  {
    id: "mid-gerbera-5",
    type: "gerbera",
    depth: "midground",
    x: 94,
    y: 102,
    scale: 0.97,
    rotation: 7,
    variant: 0,
    visibleIn: ["day", "sunset", "night"],
  },
  {
    id: "mid-tulip-far-right",
    type: "tulip",
    depth: "midground",
    x: 103,
    y: 100,
    scale: 1.05,
    rotation: 4,
    variant: 2,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // FOREGROUND  (scale 1.7–2.4, bleeds past both edges)
  // Irregular spacing — intentionally organic, not evenly distributed.
  // ─────────────────────────────────────────────────────────────────────────

  {
    id: "front-tulip-edge-left",
    type: "tulip",
    depth: "foreground",
    x: -12,
    y: 110,
    scale: 2.10,
    rotation: -14,
    variant: 2,
    essential: true,
  },
  {
    id: "front-gerbera-1",
    type: "gerbera",
    depth: "foreground",
    x: 3,
    y: 112,
    scale: 1.85,
    rotation: 6,
    variant: 1,
    essential: true,
    visibleIn: ["day", "sunset", "night"],
  },
  {
    id: "front-tulip-1",
    type: "tulip",
    depth: "foreground",
    x: 16,
    y: 109,
    scale: 2.00,
    rotation: -8,
    variant: 0,
    essential: true,
  },
  {
    id: "front-tulip-2",
    type: "tulip",
    depth: "foreground",
    x: 28,
    y: 111,
    scale: 1.78,
    rotation: 9,
    variant: 1,
    essential: true,
  },
  {
    id: "front-gerbera-2",
    type: "gerbera",
    depth: "foreground",
    x: 39,
    y: 113,
    scale: 1.90,
    rotation: -5,
    variant: 0,
    essential: true,
    visibleIn: ["day", "sunset", "night"],
  },
  {
    id: "front-tulip-3",
    type: "tulip",
    depth: "foreground",
    x: 50,
    y: 110,
    scale: 2.30,
    rotation: 4,
    variant: 2,
    essential: true,
  },
  {
    id: "front-gerbera-3",
    type: "gerbera",
    depth: "foreground",
    x: 62,
    y: 112,
    scale: 1.95,
    rotation: -7,
    variant: 2,
    essential: true,
    visibleIn: ["day", "sunset", "night"],
  },
  {
    id: "front-tulip-4",
    type: "tulip",
    depth: "foreground",
    x: 74,
    y: 109,
    scale: 2.20,
    rotation: 11,
    variant: 0,
    essential: true,
  },
  {
    id: "front-tulip-5",
    type: "tulip",
    depth: "foreground",
    x: 84,
    y: 111,
    scale: 1.82,
    rotation: -10,
    variant: 1,
    essential: true,
  },
  {
    id: "front-gerbera-4",
    type: "gerbera",
    depth: "foreground",
    x: 94,
    y: 112,
    scale: 2.00,
    rotation: 6,
    variant: 1,
    essential: true,
    visibleIn: ["day", "sunset", "night"],
  },
  {
    id: "front-tulip-edge-right",
    type: "tulip",
    depth: "foreground",
    x: 108,
    y: 110,
    scale: 2.15,
    rotation: -12,
    variant: 0,
    essential: true,
  },
];

export const GARDEN_GRASS: GardenGrass[] = [
  { id: "grass-1",  x: -4,  y: 104, scale: 1.1 },
  { id: "grass-2",  x: 4,   y: 109, scale: 1.0 },
  { id: "grass-3",  x: 11,  y: 105, scale: 0.85 },
  { id: "grass-4",  x: 18,  y: 107, scale: 0.9,  flip: true },
  { id: "grass-5",  x: 26,  y: 104, scale: 1.05 },
  { id: "grass-6",  x: 34,  y: 108, scale: 0.8,  flip: true },
  { id: "grass-7",  x: 42,  y: 105, scale: 1.0 },
  { id: "grass-8",  x: 50,  y: 107, scale: 0.95, flip: true },
  { id: "grass-9",  x: 58,  y: 104, scale: 1.1 },
  { id: "grass-10", x: 66,  y: 108, scale: 0.85 },
  { id: "grass-11", x: 74,  y: 105, scale: 1.0,  flip: true },
  { id: "grass-12", x: 82,  y: 107, scale: 0.9 },
  { id: "grass-13", x: 90,  y: 104, scale: 1.05, flip: true },
  { id: "grass-14", x: 98,  y: 108, scale: 0.8 },
  { id: "grass-15", x: 106, y: 105, scale: 1.0 },
];
