import type {
  GardenFlower,
  GardenGrass,
} from "../components/garden/types";

export const GARDEN_FLOWERS:
  GardenFlower[] = [
  /*
   * BACKGROUND
   */

  {
    id: "bg-tulip-1",
    type: "tulip",
    depth: "background",
    x: 5,
    y: 94,
    scale: 0.6,
    rotation: -7,
    variant: 0,
  },
  {
    id: "bg-gerbera-1",
    type: "gerbera",
    depth: "background",
    x: 14,
    y: 92,
    scale: 0.55,
    rotation: 5,
    variant: 1,
  },
  {
    id: "bg-tulip-2",
    type: "tulip",
    depth: "background",
    x: 24,
    y: 96,
    scale: 0.68,
    rotation: 4,
    variant: 1,
  },
  {
    id: "bg-tulip-3",
    type: "tulip",
    depth: "background",
    x: 38,
    y: 93,
    scale: 0.55,
    rotation: -4,
    variant: 2,
  },
  {
    id: "bg-gerbera-2",
    type: "gerbera",
    depth: "background",
    x: 52,
    y: 94,
    scale: 0.55,
    rotation: 7,
    variant: 0,
  },
  {
    id: "bg-tulip-4",
    type: "tulip",
    depth: "background",
    x: 65,
    y: 92,
    scale: 0.65,
    rotation: -6,
    variant: 0,
  },
  {
    id: "bg-gerbera-3",
    type: "gerbera",
    depth: "background",
    x: 77,
    y: 95,
    scale: 0.52,
    rotation: 4,
    variant: 2,
    visibleIn: ["sunset", "night"],
  },
  {
    id: "bg-tulip-5",
    type: "tulip",
    depth: "background",
    x: 91,
    y: 93,
    scale: 0.62,
    rotation: -4,
    variant: 1,
  },

  /*
   * MIDGROUND
   */

  {
    id: "mid-tulip-1",
    type: "tulip",
    depth: "midground",
    x: 2,
    y: 100,
    scale: 0.95,
    rotation: -10,
    variant: 1,
  },
  {
    id: "mid-gerbera-1",
    type: "gerbera",
    depth: "midground",
    x: 11,
    y: 101,
    scale: 0.88,
    rotation: 8,
    variant: 0,
  },
  {
    id: "mid-tulip-2",
    type: "tulip",
    depth: "midground",
    x: 22,
    y: 99,
    scale: 1,
    rotation: 4,
    variant: 0,
    essential: true,
  },
  {
    id: "mid-gerbera-2",
    type: "gerbera",
    depth: "midground",
    x: 34,
    y: 102,
    scale: 0.85,
    rotation: -5,
    variant: 2,
  },
  {
    id: "mid-tulip-3",
    type: "tulip",
    depth: "midground",
    x: 46,
    y: 98,
    scale: 1.08,
    rotation: 4,
    variant: 2,
  },
  {
    id: "mid-tulip-4",
    type: "tulip",
    depth: "midground",
    x: 59,
    y: 101,
    scale: 0.9,
    rotation: -4,
    variant: 1,
  },
  {
    id: "mid-gerbera-3",
    type: "gerbera",
    depth: "midground",
    x: 70,
    y: 99,
    scale: 0.95,
    rotation: 5,
    variant: 1,
    essential: true,
    visibleIn: ["sunset", "night"],
  },
  {
    id: "mid-tulip-5",
    type: "tulip",
    depth: "midground",
    x: 82,
    y: 101,
    scale: 1,
    rotation: -7,
    variant: 0,
  },
  {
    id: "mid-gerbera-4",
    type: "gerbera",
    depth: "midground",
    x: 94,
    y: 100,
    scale: 0.9,
    rotation: 6,
    variant: 2,
    visibleIn: ["sunset", "night"],
  },

  /*
   * FOREGROUND
   */

  {
    id: "front-tulip-1",
    type: "tulip",
    depth: "foreground",
    x: -2,
    y: 108,
    scale: 1.45,
    rotation: -12,
    variant: 2,
    essential: true,
  },
  {
    id: "front-gerbera-1",
    type: "gerbera",
    depth: "foreground",
    x: 12,
    y: 109,
    scale: 1.3,
    rotation: 5,
    variant: 1,
    essential: true,
  },
  {
    id: "front-tulip-2",
    type: "tulip",
    depth: "foreground",
    x: 27,
    y: 108,
    scale: 1.5,
    rotation: 7,
    variant: 0,
    essential: true,
  },
  {
    id: "front-gerbera-2",
    type: "gerbera",
    depth: "foreground",
    x: 45,
    y: 110,
    scale: 1.35,
    rotation: -4,
    variant: 0,
    essential: true,
  },
  {
    id: "front-tulip-3",
    type: "tulip",
    depth: "foreground",
    x: 61,
    y: 108,
    scale: 1.55,
    rotation: -5,
    variant: 1,
    essential: true,
  },
  {
    id: "front-gerbera-3",
    type: "gerbera",
    depth: "foreground",
    x: 79,
    y: 110,
    scale: 1.32,
    rotation: 6,
    variant: 2,
    essential: true,
  },
  {
    id: "front-tulip-4",
    type: "tulip",
    depth: "foreground",
    x: 96,
    y: 108,
    scale: 1.48,
    rotation: -8,
    variant: 0,
    essential: true,
  },
];

export const GARDEN_GRASS:
  GardenGrass[] = [
  {
    id: "grass-1",
    x: -4,
    y: 104,
    scale: 1.1,
  },
  {
    id: "grass-2",
    x: 6,
    y: 110,
    scale: 1,
  },
  {
    id: "grass-3",
    x: 17,
    y: 100,
    scale: 0.8,
  },
  {
    id: "grass-4",
    x: 30,
    y: 106,
    scale: 0.9,
    flip: true,
  },
  {
    id: "grass-5",
    x: 42,
    y: 98,
    scale: 0.7,
  },
  {
    id: "grass-6",
    x: 54,
    y: 108,
    scale: 1,
  },
  {
    id: "grass-7",
    x: 66,
    y: 97,
    scale: 0.75,
  },
  {
    id: "grass-8",
    x: 78,
    y: 107,
    scale: 0.95,
    flip: true,
  },
  {
    id: "grass-9",
    x: 88,
    y: 96,
    scale: 0.7,
  },
  {
    id: "grass-10",
    x: 97,
    y: 105,
    scale: 1,
  },
  {
    id: "grass-11",
    x: 100,
    y: 110,
    scale: 0.85,
  },
  {
    id: "grass-12",
    x: 44,
    y: 112,
    scale: 1.05,
    flip: true,
  },
];